### PR TITLE
Fix set pars

### LINKED ISSUE #125: Improve set_pars
Currently uses a duplicated codepath from initialise and I think leaves the system inconsistent on failure

### PR DESCRIPTION
**Pull request by richfitz**
This PR fixes handling of set_pars

* works for multiple data
* never leaves the model in an inconsistent state (either it will set all parameters or none)
* now requires that the model never changes size (number of parameter sets, size of the state) which we already assume in mcstate

Fixes #125

### CODE REVIEW

File: DESCRIPTION [hunk 1]
```diff
@@ -1,6 +1,6 @@
 Package: dust
 Title: Iterate Multiple Realisations of Stochastic Models
-Version: 0.7.6
+Version: 0.7.7
```
Comment (johnlees) [inline DESCRIPTION]:
```suggestion
Version: 0.7.8
```

File: inst/include/dust/dust.hpp [hunk 2]
```diff
@@ -567,41 +556,63 @@ class Dust {
...
+        p.size();
+      throw std::invalid_argument(msg.str());
+    }
+    if (_particles.size() == n_particles) {
+#ifdef _OPENMP
+      #pragma omp parallel for schedule(static) num_threads(_n_threads)
+#endif
+      for (size_t i = 0; i < n_particles; ++i) {
+        _particles[i].set_pars(p, set_state);
+      }
```
Comment (johnlees) [inline inst/include/dust/dust.hpp:575]: This branch is to save on allocations if np isn't changing?

File: inst/include/dust/interface.hpp [hunk 3]
```diff
@@ -41,6 +41,8 @@ cpp11::sexp create_matrix(size_t nrow, size_t ncol, T& pars);
 template <typename T>
 cpp11::sexp create_array(const std::vector<size_t>& dim, T& pars);
 
+inline void check_pars_multi(cpp11::list pars, size_t n);
```
Comment (johnlees) [inline inst/include/dust/interface.hpp:44]: inline 👀 
(I approve)

File: inst/include/dust/dust.hpp [hunk 4]
```diff
@@ -567,41 +556,63 @@ class Dust {
...
+#endif
+      for (size_t i = 0; i < _n_particles_total; ++i) {
+        _particles[i].set_pars(p[i / n_particles], set_state);
+      }
+    } else {
+      _particles.clear();
+      _particles.reserve(n_particles * _n_pars);
+      for (size_t i = 0; i < _n_pars; ++i) {
+        for (size_t j = 0; j < n_particles; ++j) {
+          _particles.push_back(p[i]);
```
Comment (johnlees) [inline inst/include/dust/dust.hpp:612]: Could also have openmp here if you s/reserve/resize/ and insert at `i * n_particles + j` (but I'm easy, not sure how much difference it would make anyway)

**Review by johnlees — APPROVED** [review]

File: inst/include/dust/dust.hpp (hunk 2 above)
Comment (richfitz) [reply inst/include/dust/dust.hpp:575]: yes, it also lets us do this in parallel (the previous branch can't be done in parallel because we use push_back and we can't resize first because the particles aren't default-constructible)

File: inst/include/dust/interface.hpp (hunk 3 above)
Comment (richfitz) [reply inst/include/dust/interface.hpp:44]: has to be inline to avoid multiple definition errors :)

File: inst/include/dust/dust.hpp (hunk 4 above)
Comment (richfitz) [reply inst/include/dust/dust.hpp:612]: I looked into this and it's hard if we can't default construct. there are some workarounds to make push_back work in parallel but they are all grim

File: DESCRIPTION (hunk 1 above)
Comment (richfitz) [reply DESCRIPTION]: You managed to catch this just before I fixed that (we had to quickly sneak a fix in for a broken density function)

File: inst/include/dust/dust.hpp (hunk 4 above)
Comment (johnlees) [reply inst/include/dust/dust.hpp:612]: I previously tried one work-around using `#pragma critical` to merge lists made by each thread. Was no faster, and sometimes segfaulted in other environments

Comment (johnlees) [reply inst/include/dust/dust.hpp:612]: (so I removed it)

Comment (richfitz) [reply inst/include/dust/dust.hpp:612]: This makes me pleased I did not try! This never shows up as a big timesink normally
